# deberta_lora_optuna experiment config
# configs/deberta_lora_optuna.yaml
#https://arxiv.org/pdf/2106.09685 inspo paper
_base_: base.yaml #base file with fixed parameters

model_name: "microsoft/deberta-v3-base"
finetune_method: "lora" #tuning method
output_dir: "results/deberta_lora_optuna" #rest place
task_type: "SEQ_CLS" #model task
early_stopping_patience: 50
bias: "none"
fp16: false


#parameters from  optuna
target_modules: ["query_proj", "key_proj", "value_proj", "dense"] # as determined by experiments
weight_decay: 0.06135622195040731
warmup_ratio: 0.19204428145852243
lr_scheduler_type: "linear" #Must be see according to Lora paper
learning_rate: 1.0609624330107086e-05
r: 2
lora_alpha: 8
lora_dropout: 0.1
