#params taken from page 17 of :https://arxiv.org/pdf/2006.03654
# deberta_full experiment config
# configs/deberta_full.yaml
_base_: base.yaml

model_name: "microsoft/deberta-v3-large"
finetune_method: "full"
output_dir: "results/deberta-full"
fp16: false
learning_rate: 7.484095237447559e-06
warmup_ratio: 0.10460652415485279
weight_decay: 0.015986584841970367
num_train_epochs: 2
per_device_train_batch_size: 4
